language: php

php:
  - 5.4
  - 5.3

services:
  - mongodb

before_script:
  - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - mongo mongo_test --eval 'db.addUser("root");'

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  email:
    - eugene.kurbatov@gmail.com
